spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    function:
      definition: ingestPostgres
    stream:
      bindings:
        ingestPostgres-in-0:
          destination: ${TOPIC_IN}
          group: ${GROUP_IN}
          consumer:
            concurrency: ${CONSUMER_CONCURRENCY}
        ingestPostgres-out-0:
          destination: ${TOPIC_OUT}    # ← Publica aquí automáticamente

      binders:
        local-solace:
          type: solace
          environment:
            solace:
              java:
                host: tcp://localhost:55556
                msgVpn: default
                clientUsername: default
                clientPassword: default
                connectRetries: ${SOLACE_CONNECT_RETRIES}
                connectRetriesPerHost: ${SOLACE_CONNECT_RETRIES_PER_HOST}
                reconnectRetries: ${SOLACE_RECONNECT_RETRIES}

server:
  port: ${SERVER_PORT}
